// <copyright file="IBasicAuthCredentials.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>

namespace LogaltyCertificateIssuanceApiCerty.Standard.Authentication
{
    /// <summary>
    /// Authentication configuration interface for BasicAuth.
    /// </summary>
    public interface IBasicAuthCredentials
    {
        /// <summary>
        /// Gets string value for username.
        /// </summary>
        string Username { get; }

        /// <summary>
        /// Gets string value for password.
        /// </summary>
        string Password { get; }

        /// <summary>
        ///  Returns true if credentials matched.
        /// </summary>
        /// <param name="username"> The string value for credentials.</param>
        /// <param name="password"> The string value for credentials.</param>
        /// <returns>True if credentials matched.</returns>
        bool Equals(string username, string password);
    }
}