// <copyright file="UpdateRequest.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<UpdateRequest>),
        new[] {
            typeof(ResendRequestCase),
            typeof(CancelRequestCase)
        },
        new[] {
            "resend",
            "cancel"
        },
        "operation",
        true
    )]
    public abstract class UpdateRequest
    {
        /// <summary>
        /// This is ResendRequest case.
        /// </summary>
        /// <returns>
        /// The UpdateRequest instance, wrapping the provided ResendRequest value.
        /// </returns>
        public static UpdateRequest FromResendRequest(ResendRequest resendRequest)
        {
            return new ResendRequestCase().Set(resendRequest);
        }

        /// <summary>
        /// This is CancelRequest case.
        /// </summary>
        /// <returns>
        /// The UpdateRequest instance, wrapping the provided CancelRequest value.
        /// </returns>
        public static UpdateRequest FromCancelRequest(CancelRequest cancelRequest)
        {
            return new CancelRequestCase().Set(cancelRequest);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<ResendRequest, T> resendRequest, Func<CancelRequest, T> cancelRequest);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<ResendRequest, T> resendRequest = null, Func<CancelRequest, T> cancelRequest = null) =>
                Match(resendRequest, cancelRequest);

        [JsonConverter(typeof(UnionTypeCaseConverter<ResendRequestCase, ResendRequest>))]
        private sealed class ResendRequestCase : UpdateRequest, ICaseValue<ResendRequestCase, ResendRequest>
        {
            public ResendRequest Value;

            public override T Match<T>(Func<ResendRequest, T> resendRequest, Func<CancelRequest, T> cancelRequest) =>
                   resendRequest != null ? resendRequest(Value) : default;

            public ResendRequestCase Set(ResendRequest value)
            {
                Value = value;
                return this;
            }

            public ResendRequest Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<CancelRequestCase, CancelRequest>))]
        private sealed class CancelRequestCase : UpdateRequest, ICaseValue<CancelRequestCase, CancelRequest>
        {
            public CancelRequest Value;

            public override T Match<T>(Func<ResendRequest, T> resendRequest, Func<CancelRequest, T> cancelRequest) =>
                   cancelRequest != null ? cancelRequest(Value) : default;

            public CancelRequestCase Set(CancelRequest value)
            {
                Value = value;
                return this;
            }

            public CancelRequest Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}