// <copyright file="CancellationCode.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// CancellationCode.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CancellationCode
    {
        /// <summary>
        /// OptionZero.
        /// </summary>
        [EnumMember(Value = "OPTION_ZERO")]
        OptionZero,

        /// <summary>
        /// UserMobileChanged.
        /// </summary>
        [EnumMember(Value = "USER_MOBILE_CHANGED")]
        UserMobileChanged,

        /// <summary>
        /// SmsNotReceived.
        /// </summary>
        [EnumMember(Value = "SMS_NOT_RECEIVED")]
        SmsNotReceived,

        /// <summary>
        /// UserNoTokensAvailable.
        /// </summary>
        [EnumMember(Value = "USER_NO_TOKENS_AVAILABLE")]
        UserNoTokensAvailable,

        /// <summary>
        /// TechnicalProblems.
        /// </summary>
        [EnumMember(Value = "TECHNICAL_PROBLEMS")]
        TechnicalProblems,

        /// <summary>
        /// RcptInvalid.
        /// </summary>
        [EnumMember(Value = "RCPT_INVALID")]
        RcptInvalid,

        /// <summary>
        /// SenderUnknown.
        /// </summary>
        [EnumMember(Value = "SENDER_UNKNOWN")]
        SenderUnknown,

        /// <summary>
        /// UserDataInvalid.
        /// </summary>
        [EnumMember(Value = "USER_DATA_INVALID")]
        UserDataInvalid,

        /// <summary>
        /// DocumentDataInvalid.
        /// </summary>
        [EnumMember(Value = "DOCUMENT_DATA_INVALID")]
        DocumentDataInvalid,

        /// <summary>
        /// OtherReasons.
        /// </summary>
        [EnumMember(Value = "OTHER_REASONS")]
        OtherReasons,

        /// <summary>
        /// NotDocumentAgree.
        /// </summary>
        [EnumMember(Value = "NOT_DOCUMENT_AGREE")]
        NotDocumentAgree
    }
}