// <copyright file="CertificateModel.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// CertificateModel.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CertificateModel
    {
        /// <summary>
        /// Personalhsmfortressqes.
        /// </summary>
        [EnumMember(Value = "personal-hsm-fortress-qes")]
        Personalhsmfortressqes,

        /// <summary>
        /// Personalsw.
        /// </summary>
        [EnumMember(Value = "personal-sw")]
        Personalsw,

        /// <summary>
        /// Personalswidentity.
        /// </summary>
        [EnumMember(Value = "personal-sw-identity")]
        Personalswidentity,

        /// <summary>
        /// Personalswidentitysc.
        /// </summary>
        [EnumMember(Value = "personal-sw-identity-sc")]
        Personalswidentitysc
    }
}