// <copyright file="IdType.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// IdType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum IdType
    {
        /// <summary>
        /// Idc.
        /// </summary>
        [EnumMember(Value = "IDC")]
        Idc,

        /// <summary>
        /// Passport.
        /// </summary>
        [EnumMember(Value = "PASSPORT")]
        Passport,

        /// <summary>
        /// Tin.
        /// </summary>
        [EnumMember(Value = "TIN")]
        Tin,

        /// <summary>
        /// Other.
        /// </summary>
        [EnumMember(Value = "OTHER")]
        Other
    }
}