// <copyright file="ImageType.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// ImageType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ImageType
    {
        /// <summary>
        /// DniNie.
        /// </summary>
        [EnumMember(Value = "DNI_NIE")]
        DniNie,

        /// <summary>
        /// DniNieBack.
        /// </summary>
        [EnumMember(Value = "DNI_NIE_BACK")]
        DniNieBack,

        /// <summary>
        /// Passport.
        /// </summary>
        [EnumMember(Value = "PASSPORT")]
        Passport,

        /// <summary>
        /// DriverLicense.
        /// </summary>
        [EnumMember(Value = "DRIVER_LICENSE")]
        DriverLicense,

        /// <summary>
        /// Selfie.
        /// </summary>
        [EnumMember(Value = "SELFIE")]
        Selfie,

        /// <summary>
        /// SelfieLife.
        /// </summary>
        [EnumMember(Value = "SELFIE_LIFE")]
        SelfieLife,

        /// <summary>
        /// Photocut.
        /// </summary>
        [EnumMember(Value = "PHOTOCUT")]
        Photocut,

        /// <summary>
        /// Signature.
        /// </summary>
        [EnumMember(Value = "SIGNATURE")]
        Signature,

        /// <summary>
        /// Fingerprint.
        /// </summary>
        [EnumMember(Value = "FINGERPRINT")]
        Fingerprint
    }
}