// <copyright file="Image.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using LogaltyCertificateIssuanceApiCerty.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// Image.
    /// </summary>
    public class Image
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Image"/> class.
        /// </summary>
        public Image()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Image"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="contentType">contentType.</param>
        /// <param name="content">content.</param>
        /// <param name="hash">hash.</param>
        public Image(
            Models.ImageType? type = null,
            string contentType = null,
            string content = null,
            string hash = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Type = type;
            this.ContentType = contentType;
            this.Content = content;
            this.Hash = hash;
        }

        /// <summary>
        /// Image type:
        /// - `DNI_NIE`: Front of the ID card.
        /// - `DNI_NIE_BACK`: Back of the ID card.
        /// - `PASSPORT`: Passport image.
        /// - `DRIVER_LICENSE`: Driver's license image.
        /// - `SELFIE`: Selfie.
        /// - `SELFIE_LIFE`: Selfie with liveness proof.
        /// - `PHOTOCUT`: Cropped face image from the document.
        /// - `SIGNATURE`: Cropped handwritten signature from the document.
        /// - `FINGERPRINT`: Cropped fingerprint image from the document.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ImageType? Type { get; set; }

        /// <summary>
        /// MIME type of the image (e.g. `image/jpg`, `image/png`).
        /// </summary>
        [JsonProperty("contentType", NullValueHandling = NullValueHandling.Ignore)]
        public string ContentType { get; set; }

        /// <summary>
        /// Image content encoded in Base64.
        /// </summary>
        [JsonProperty("content", NullValueHandling = NullValueHandling.Ignore)]
        public string Content { get; set; }

        /// <summary>
        /// Hash of the image content.
        /// </summary>
        [JsonProperty("hash", NullValueHandling = NullValueHandling.Ignore)]
        public string Hash { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Image : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {(this.Type == null ? "null" : this.Type.ToString())}");
            toStringOutput.Add($"ContentType = {this.ContentType ?? "null"}");
            toStringOutput.Add($"Content = {this.Content ?? "null"}");
            toStringOutput.Add($"Hash = {this.Hash ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}