// <copyright file="NoticeMethod.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// NoticeMethod.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum NoticeMethod
    {
        /// <summary>
        /// None.
        /// </summary>
        [EnumMember(Value = "NONE")]
        None,

        /// <summary>
        /// Email.
        /// </summary>
        [EnumMember(Value = "EMAIL")]
        Email,

        /// <summary>
        /// Sms.
        /// </summary>
        [EnumMember(Value = "SMS")]
        Sms
    }
}