// <copyright file="OauthScope.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// OauthScope.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum OauthScope
    {
        /// <summary>
        /// EnumCertycertificaterequest.
        /// </summary>
        [EnumMember(Value = "certy/certificate-request")]
        EnumCertycertificaterequest
    }
}