// <copyright file="Profile.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using LogaltyCertificateIssuanceApiCerty.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// Profile.
    /// </summary>
    public class Profile
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Profile"/> class.
        /// </summary>
        public Profile()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Profile"/> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="phone">phone.</param>
        /// <param name="idtype">idtype.</param>
        /// <param name="idcountry">idcountry.</param>
        /// <param name="idnumber">idnumber.</param>
        /// <param name="surname1">surname1.</param>
        /// <param name="surname2">surname2.</param>
        /// <param name="email">email.</param>
        /// <param name="validation">validation.</param>
        public Profile(
            string name,
            string phone,
            Models.IdType? idtype = Models.IdType.Idc,
            string idcountry = "EN",
            string idnumber = null,
            string surname1 = null,
            string surname2 = null,
            string email = null,
            List<Models.ValidationRule> validation = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Idtype = idtype;
            this.Idcountry = idcountry;
            this.Idnumber = idnumber;
            this.Name = name;
            this.Surname1 = surname1;
            this.Surname2 = surname2;
            this.Phone = phone;
            this.Email = email;
            this.Validation = validation;
        }

        /// <summary>
        /// Gets or sets Idtype.
        /// </summary>
        [JsonProperty("idtype", NullValueHandling = NullValueHandling.Ignore)]
        public Models.IdType? Idtype { get; set; }

        /// <summary>
        /// Issuing country of the document, coded according to ISO 3166-1. Default is `EN`.
        /// </summary>
        [JsonProperty("idcountry", NullValueHandling = NullValueHandling.Ignore)]
        public string Idcountry { get; set; }

        /// <summary>
        /// Identity document number.
        /// </summary>
        [JsonProperty("idnumber", NullValueHandling = NullValueHandling.Ignore)]
        public string Idnumber { get; set; }

        /// <summary>
        /// End-user's given name.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// End-user's first family name.
        /// </summary>
        [JsonProperty("surname1", NullValueHandling = NullValueHandling.Ignore)]
        public string Surname1 { get; set; }

        /// <summary>
        /// End-user's second family name.
        /// </summary>
        [JsonProperty("surname2", NullValueHandling = NullValueHandling.Ignore)]
        public string Surname2 { get; set; }

        /// <summary>
        /// End-user's telephone number. Required for SMS notifications.
        /// </summary>
        [JsonProperty("phone")]
        public string Phone { get; set; }

        /// <summary>
        /// End-user's e-mail address. Required for e-mail notifications.
        /// </summary>
        [JsonProperty("email", NullValueHandling = NullValueHandling.Ignore)]
        public string Email { get; set; }

        /// <summary>
        /// Additional validations to perform on the user's data.
        /// </summary>
        [JsonProperty("validation", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ValidationRule> Validation { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Profile : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Idtype = {(this.Idtype == null ? "null" : this.Idtype.ToString())}");
            toStringOutput.Add($"Idcountry = {this.Idcountry ?? "null"}");
            toStringOutput.Add($"Idnumber = {this.Idnumber ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Surname1 = {this.Surname1 ?? "null"}");
            toStringOutput.Add($"Surname2 = {this.Surname2 ?? "null"}");
            toStringOutput.Add($"Phone = {this.Phone ?? "null"}");
            toStringOutput.Add($"Email = {this.Email ?? "null"}");
            toStringOutput.Add($"Validation = {(this.Validation == null ? "null" : $"[{string.Join(", ", this.Validation)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}