// <copyright file="ResendRequest.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using LogaltyCertificateIssuanceApiCerty.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// ResendRequest.
    /// </summary>
    public class ResendRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResendRequest"/> class.
        /// </summary>
        public ResendRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResendRequest"/> class.
        /// </summary>
        /// <param name="operation">operation.</param>
        /// <param name="noticeMethod">noticeMethod.</param>
        /// <param name="contact">contact.</param>
        public ResendRequest(
            string operation,
            Models.NoticeMethod? noticeMethod = null,
            string contact = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Operation = operation;
            this.NoticeMethod = noticeMethod;
            this.Contact = contact;
        }

        /// <summary>
        /// Fixed value `resend`.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("operation")]
        [JsonRequired]
        public string Operation { get; set; }

        /// <summary>
        /// Notification channel used to give the end-user access to the system:
        /// - `NONE`: No notification is sent; only a synchronous access URL is returned.
        /// - `EMAIL`: An asynchronous access link is sent by e-mail.
        /// - `SMS`: An asynchronous access link is sent by SMS.
        /// </summary>
        [JsonProperty("noticeMethod", NullValueHandling = NullValueHandling.Ignore)]
        public Models.NoticeMethod? NoticeMethod { get; set; }

        /// <summary>
        /// Alternative contact information to use instead of the one on the original request.
        /// - For `EMAIL`: must be a valid e-mail address.
        /// - For `SMS`: must be a valid phone number.
        /// If the process has not yet been accessed by the user, the contact on the request is updated.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("contact", NullValueHandling = NullValueHandling.Ignore)]
        public string Contact { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ResendRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Operation = {this.Operation ?? "null"}");
            toStringOutput.Add($"NoticeMethod = {(this.NoticeMethod == null ? "null" : this.NoticeMethod.ToString())}");
            toStringOutput.Add($"Contact = {this.Contact ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}