// <copyright file="ResendOperation.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// ResendOperation.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ResendOperation
    {
        /// <summary>
        /// Resend.
        /// </summary>
        [EnumMember(Value = "resend")]
        Resend
    }
}