// <copyright file="TransactionStatus.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using LogaltyCertificateIssuanceApiCerty.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// TransactionStatus.
    /// </summary>
    public class TransactionStatus
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionStatus"/> class.
        /// </summary>
        public TransactionStatus()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionStatus"/> class.
        /// </summary>
        /// <param name="code">code.</param>
        /// <param name="certId">certId.</param>
        /// <param name="created">created.</param>
        /// <param name="profileData">profileData.</param>
        /// <param name="externalId">externalId.</param>
        /// <param name="state">state.</param>
        /// <param name="stateDate">stateDate.</param>
        /// <param name="result">result.</param>
        /// <param name="resultDate">resultDate.</param>
        /// <param name="coreCancelCode">coreCancelCode.</param>
        /// <param name="coreCancelReason">coreCancelReason.</param>
        /// <param name="activationUrl">activationUrl.</param>
        public TransactionStatus(
            Guid? code = null,
            string certId = null,
            long? created = null,
            Models.Profile profileData = null,
            string externalId = null,
            Models.TransactionState? state = null,
            long? stateDate = null,
            Models.TransactionResult? result = null,
            long? resultDate = null,
            Models.CancellationCode? coreCancelCode = null,
            string coreCancelReason = null,
            string activationUrl = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Code = code;
            this.CertId = certId;
            this.Created = created;
            this.ProfileData = profileData;
            this.ExternalId = externalId;
            this.State = state;
            this.StateDate = stateDate;
            this.Result = result;
            this.ResultDate = resultDate;
            this.CoreCancelCode = coreCancelCode;
            this.CoreCancelReason = coreCancelReason;
            this.ActivationUrl = activationUrl;
        }

        /// <summary>
        /// Transaction's unique identifier in Logalty (UUIDv4 format).
        /// </summary>
        [JsonProperty("code", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? Code { get; set; }

        /// <summary>
        /// Unique certificate identifier in Logalty.
        /// </summary>
        [JsonProperty("certId", NullValueHandling = NullValueHandling.Ignore)]
        public string CertId { get; set; }

        /// <summary>
        /// Transaction creation date in epoch (milliseconds) format.
        /// </summary>
        [JsonProperty("created", NullValueHandling = NullValueHandling.Ignore)]
        public long? Created { get; set; }

        /// <summary>
        /// Gets or sets ProfileData.
        /// </summary>
        [JsonProperty("profileData", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Profile ProfileData { get; set; }

        /// <summary>
        /// Unique identifier in the client system external to Logalty.
        /// </summary>
        [JsonProperty("externalId", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Transaction state:
        /// - `0`: CREATED — Transaction created.
        /// - `1`: ACCESS_SENT — Access notification sent.
        /// - `10`: PENDING_CERTIFICATE_CONTRACT_SIGNATURE — Pending signature of the certificate issuance contract.
        /// - `11`: PENDING_CERTIFICATE_VALIDATION — Pending validation by the video operator.
        /// - `12`: CLOSED — Transaction closed.
        /// - `13`: PENDING_CERTIFICATE_ISSUING — Pending issuance by the RA operator.
        /// - `14`: PENDING_CERTIFICATE_ACTIVATION — Pending certificate activation by the end-user.
        /// - `15`: PENDING_CERTIFICATE_DOWNLOAD — Pending certificate download by the end-user (software support only).
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TransactionState? State { get; set; }

        /// <summary>
        /// Date of last status change in epoch format.
        /// </summary>
        [JsonProperty("stateDate", NullValueHandling = NullValueHandling.Ignore)]
        public long? StateDate { get; set; }

        /// <summary>
        /// Transaction result:
        /// - `7`: COMPLETED — Process completed and certificate generated.
        /// - `8`: USER_REJECT — End-user rejected the process.
        /// - `9901`: ERROR_SENDING_ACCESS — Error sending the access notification.
        /// - `9910`: ERROR_CERTIFICATE_CONTRACT_SIGNATURE — Error in the signature of the issuance contract.
        /// - `9911`: ERROR_CERTIFICATE_CONTRACT_IDENTIFICATION — Error identifying the user during contract signing.
        /// - `9912`: ERROR_CERTIFICATE_VALIDATION_REJECTED — Validation rejected by the video operator.
        /// - `9913`: ERROR_CERTIFICATE_ISSUING_REJECTED — Issuance rejected by the RA operator.
        /// - `9914`: ERROR_CERTIFICATE_ACTIVATION — Certificate activation error.
        /// - `99906`: TIME_EXPIRED — Transaction closed due to expired time.
        /// - `99908`: OCR_FAILED — OCR validation exceeded.
        /// - `99909`: OCR_FAILED — Maximum number of validation attempts exceeded (permissive).
        /// - `99910`: DNI_WITHOUT_CHIP — DNI does not have chip or is not readable.
        /// - `99915`: TIME_AUTH_EXPIRED — Time for authorization exceeded.
        /// - `99932`: CLOSED_BY_REMITANCE — Transaction cancelled by the customer.
        /// - `99940`: DELETED_BY_SENDER — Reserved status.
        /// - `99945`: ERROR_ID_NUMBER — Error in the identification number.
        /// - `99990`: CLOSED_BY_MAINTENANCE — Reserved status.
        /// </summary>
        [JsonProperty("result", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TransactionResult? Result { get; set; }

        /// <summary>
        /// Result date in epoch format.
        /// </summary>
        [JsonProperty("resultDate", NullValueHandling = NullValueHandling.Ignore)]
        public long? ResultDate { get; set; }

        /// <summary>
        /// Cancellation code provided by the end-user:
        /// - `OPTION_ZERO`: No reason indicated.
        /// - `USER_MOBILE_CHANGED`: User changed their phone number.
        /// - `SMS_NOT_RECEIVED`: User did not receive the SMS.
        /// - `USER_NO_TOKENS_AVAILABLE`: User does not have a cell phone.
        /// - `TECHNICAL_PROBLEMS`: Technical problems reported by the user.
        /// - `RCPT_INVALID`: Transaction not directed at the user.
        /// - `SENDER_UNKNOWN`: User does not know the sender.
        /// - `USER_DATA_INVALID`: User data is incorrect.
        /// - `DOCUMENT_DATA_INVALID`: Documentation is incorrect.
        /// - `OTHER_REASONS`: Other problems.
        /// - `NOT_DOCUMENT_AGREE`: User does not agree with the documentation.
        /// </summary>
        [JsonProperty("coreCancelCode", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CancellationCode? CoreCancelCode { get; set; }

        /// <summary>
        /// Free-text reason for cancellation.
        /// </summary>
        [JsonProperty("coreCancelReason", NullValueHandling = NullValueHandling.Ignore)]
        public string CoreCancelReason { get; set; }

        /// <summary>
        /// URL to access the certificate activation process.
        /// </summary>
        [JsonProperty("activationUrl", NullValueHandling = NullValueHandling.Ignore)]
        public string ActivationUrl { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TransactionStatus : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Code = {(this.Code == null ? "null" : this.Code.ToString())}");
            toStringOutput.Add($"CertId = {this.CertId ?? "null"}");
            toStringOutput.Add($"Created = {(this.Created == null ? "null" : this.Created.ToString())}");
            toStringOutput.Add($"ProfileData = {(this.ProfileData == null ? "null" : this.ProfileData.ToString())}");
            toStringOutput.Add($"ExternalId = {this.ExternalId ?? "null"}");
            toStringOutput.Add($"State = {(this.State == null ? "null" : this.State.ToString())}");
            toStringOutput.Add($"StateDate = {(this.StateDate == null ? "null" : this.StateDate.ToString())}");
            toStringOutput.Add($"Result = {(this.Result == null ? "null" : this.Result.ToString())}");
            toStringOutput.Add($"ResultDate = {(this.ResultDate == null ? "null" : this.ResultDate.ToString())}");
            toStringOutput.Add($"CoreCancelCode = {(this.CoreCancelCode == null ? "null" : this.CoreCancelCode.ToString())}");
            toStringOutput.Add($"CoreCancelReason = {this.CoreCancelReason ?? "null"}");
            toStringOutput.Add($"ActivationUrl = {this.ActivationUrl ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}