// <copyright file="TransactionResult.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// TransactionResult.
    /// </summary>

    [JsonConverter(typeof(NumberEnumConverter))]
    public enum TransactionResult
    {
        /// <summary>
        /// Enum7.
        /// </summary>
        Enum7 = 7,

        /// <summary>
        /// Enum8.
        /// </summary>
        Enum8 = 8,

        /// <summary>
        /// Enum9901.
        /// </summary>
        Enum9901 = 9901,

        /// <summary>
        /// Enum9910.
        /// </summary>
        Enum9910 = 9910,

        /// <summary>
        /// Enum9911.
        /// </summary>
        Enum9911 = 9911,

        /// <summary>
        /// Enum9912.
        /// </summary>
        Enum9912 = 9912,

        /// <summary>
        /// Enum9913.
        /// </summary>
        Enum9913 = 9913,

        /// <summary>
        /// Enum9914.
        /// </summary>
        Enum9914 = 9914,

        /// <summary>
        /// Enum99906.
        /// </summary>
        Enum99906 = 99906,

        /// <summary>
        /// Enum99908.
        /// </summary>
        Enum99908 = 99908,

        /// <summary>
        /// Enum99909.
        /// </summary>
        Enum99909 = 99909,

        /// <summary>
        /// Enum99910.
        /// </summary>
        Enum99910 = 99910,

        /// <summary>
        /// Enum99915.
        /// </summary>
        Enum99915 = 99915,

        /// <summary>
        /// Enum99932.
        /// </summary>
        Enum99932 = 99932,

        /// <summary>
        /// Enum99940.
        /// </summary>
        Enum99940 = 99940,

        /// <summary>
        /// Enum99945.
        /// </summary>
        Enum99945 = 99945,

        /// <summary>
        /// Enum99990.
        /// </summary>
        Enum99990 = 99990
    }
}