// <copyright file="TransactionState.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// TransactionState.
    /// </summary>

    [JsonConverter(typeof(NumberEnumConverter))]
    public enum TransactionState
    {
        /// <summary>
        /// Enum0.
        /// </summary>
        Enum0 = 0,

        /// <summary>
        /// Enum1.
        /// </summary>
        Enum1 = 1,

        /// <summary>
        /// Enum10.
        /// </summary>
        Enum10 = 10,

        /// <summary>
        /// Enum11.
        /// </summary>
        Enum11 = 11,

        /// <summary>
        /// Enum12.
        /// </summary>
        Enum12 = 12,

        /// <summary>
        /// Enum13.
        /// </summary>
        Enum13 = 13,

        /// <summary>
        /// Enum14.
        /// </summary>
        Enum14 = 14,

        /// <summary>
        /// Enum15.
        /// </summary>
        Enum15 = 15
    }
}