// <copyright file="TransactionRequest.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using LogaltyCertificateIssuanceApiCerty.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// TransactionRequest.
    /// </summary>
    public class TransactionRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionRequest"/> class.
        /// </summary>
        public TransactionRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionRequest"/> class.
        /// </summary>
        /// <param name="idModel">idModel.</param>
        /// <param name="profileData">profileData.</param>
        /// <param name="durationData">durationData.</param>
        /// <param name="supportData">supportData.</param>
        /// <param name="externalId">externalId.</param>
        /// <param name="duplicateKeyOff">duplicateKeyOff.</param>
        /// <param name="urlBack">urlBack.</param>
        /// <param name="noticeMethod">noticeMethod.</param>
        /// <param name="time2Close">time2close.</param>
        /// <param name="locale">locale.</param>
        public TransactionRequest(
            Models.CertificateModel idModel,
            Models.Profile profileData,
            Models.Duration durationData = null,
            Models.Support supportData = null,
            string externalId = null,
            bool? duplicateKeyOff = false,
            string urlBack = null,
            Models.NoticeMethod? noticeMethod = null,
            string time2Close = "30d",
            string locale = "es-ES")
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.IdModel = idModel;
            this.ProfileData = profileData;
            this.DurationData = durationData;
            this.SupportData = supportData;
            this.ExternalId = externalId;
            this.DuplicateKeyOff = duplicateKeyOff;
            this.UrlBack = urlBack;
            this.NoticeMethod = noticeMethod;
            this.Time2Close = time2Close;
            this.Locale = locale;
        }

        /// <summary>
        /// Certificate model:
        /// - `personal-hsm-fortress-qes`: Qualified personal certificate (QES) hosted in the cloud (FirmaCloud).
        /// - `personal-sw`: Qualified personal certificate (AES) in software support.
        /// - `personal-sw-identity`: Qualified personal certificate (AES) hosted in the cloud (FirmaCloud).
        /// - `personal-sw-identity-sc`: Qualified personal certificate (AES) hosted in Client System (SC) in cloud. Does not require end-user activation.
        /// </summary>
        [JsonProperty("idModel")]
        public Models.CertificateModel IdModel { get; set; }

        /// <summary>
        /// Gets or sets ProfileData.
        /// </summary>
        [JsonProperty("profileData")]
        public Models.Profile ProfileData { get; set; }

        /// <summary>
        /// Gets or sets DurationData.
        /// </summary>
        [JsonProperty("durationData", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Duration DurationData { get; set; }

        /// <summary>
        /// Gets or sets SupportData.
        /// </summary>
        [JsonProperty("supportData", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Support SupportData { get; set; }

        /// <summary>
        /// Unique identifier in the client system external to Logalty. Can be used to search transactions.
        /// </summary>
        [JsonProperty("externalId", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalId { get; set; }

        /// <summary>
        /// When combined with `externalId`, allows two transactions with the same external identifier
        /// to be registered. By default the external identifier is unique and duplicate use is not allowed.
        /// </summary>
        [JsonProperty("duplicateKeyOff", NullValueHandling = NullValueHandling.Ignore)]
        public bool? DuplicateKeyOff { get; set; }

        /// <summary>
        /// Redirect URL where the end-user will be redirected after process completion (GET method).
        /// The following query parameters are appended automatically:
        /// - `code`: Unique transaction identifier in Logalty.
        /// - `externalid`: External identifier (URL-encoded), if provided.
        /// - `process`: `issuing` (certificate issuance flow) or `activation` (certificate activation flow).
        /// - `status`: `ok`, `cancelled`, `error`, or `exit`.
        /// </summary>
        [JsonProperty("urlBack", NullValueHandling = NullValueHandling.Ignore)]
        public string UrlBack { get; set; }

        /// <summary>
        /// Notification channel used to give the end-user access to the system:
        /// - `NONE`: No notification is sent; only a synchronous access URL is returned.
        /// - `EMAIL`: An asynchronous access link is sent by e-mail.
        /// - `SMS`: An asynchronous access link is sent by SMS.
        /// </summary>
        [JsonProperty("noticeMethod", NullValueHandling = NullValueHandling.Ignore)]
        public Models.NoticeMethod? NoticeMethod { get; set; }

        /// <summary>
        /// Validity period of the transaction. Accepts a numeric value followed by a unit:
        /// `m` (minutes), `h` (hours), `d` (days). After this period the transaction is
        /// automatically closed with result `TIME_EXPIRED`. Default: `30d`.
        /// </summary>
        [JsonProperty("time2close", NullValueHandling = NullValueHandling.Ignore)]
        public string Time2Close { get; set; }

        /// <summary>
        /// Language of the transaction in IETF format. Default is `es-ES`.
        /// </summary>
        [JsonProperty("locale", NullValueHandling = NullValueHandling.Ignore)]
        public string Locale { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TransactionRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"IdModel = {this.IdModel}");
            toStringOutput.Add($"ProfileData = {(this.ProfileData == null ? "null" : this.ProfileData.ToString())}");
            toStringOutput.Add($"DurationData = {(this.DurationData == null ? "null" : this.DurationData.ToString())}");
            toStringOutput.Add($"SupportData = {(this.SupportData == null ? "null" : this.SupportData.ToString())}");
            toStringOutput.Add($"ExternalId = {this.ExternalId ?? "null"}");
            toStringOutput.Add($"DuplicateKeyOff = {(this.DuplicateKeyOff == null ? "null" : this.DuplicateKeyOff.ToString())}");
            toStringOutput.Add($"UrlBack = {this.UrlBack ?? "null"}");
            toStringOutput.Add($"NoticeMethod = {(this.NoticeMethod == null ? "null" : this.NoticeMethod.ToString())}");
            toStringOutput.Add($"Time2Close = {this.Time2Close ?? "null"}");
            toStringOutput.Add($"Locale = {this.Locale ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}