// <copyright file="ValidationCondition.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// ValidationCondition.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ValidationCondition
    {
        /// <summary>
        /// Equal.
        /// </summary>
        [EnumMember(Value = "EQUAL")]
        Equal,

        /// <summary>
        /// NotEqual.
        /// </summary>
        [EnumMember(Value = "NOT_EQUAL")]
        NotEqual,

        /// <summary>
        /// Between.
        /// </summary>
        [EnumMember(Value = "BETWEEN")]
        Between,

        /// <summary>
        /// GreaterThan.
        /// </summary>
        [EnumMember(Value = "GREATER_THAN")]
        GreaterThan,

        /// <summary>
        /// LesserThan.
        /// </summary>
        [EnumMember(Value = "LESSER_THAN")]
        LesserThan,

        /// <summary>
        /// GreaterEqualThan.
        /// </summary>
        [EnumMember(Value = "GREATER_EQUAL_THAN")]
        GreaterEqualThan,

        /// <summary>
        /// LesserEqualThan.
        /// </summary>
        [EnumMember(Value = "LESSER_EQUAL_THAN")]
        LesserEqualThan,

        /// <summary>
        /// In.
        /// </summary>
        [EnumMember(Value = "IN")]
        In,

        /// <summary>
        /// NotIn.
        /// </summary>
        [EnumMember(Value = "NOT_IN")]
        NotIn
    }
}