// <copyright file="ValidationRule.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using LogaltyCertificateIssuanceApiCerty.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// ValidationRule.
    /// </summary>
    public class ValidationRule
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationRule"/> class.
        /// </summary>
        public ValidationRule()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationRule"/> class.
        /// </summary>
        /// <param name="condition">condition.</param>
        /// <param name="fieldName">fieldName.</param>
        /// <param name="mValue">value.</param>
        public ValidationRule(
            Models.ValidationCondition condition,
            Models.ValidatableAttribute fieldName,
            string mValue)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Condition = condition;
            this.FieldName = fieldName;
            this.MValue = mValue;
        }

        /// <summary>
        /// Condition to apply when validating an OCR attribute.
        /// </summary>
        [JsonProperty("condition")]
        public Models.ValidationCondition Condition { get; set; }

        /// <summary>
        /// OCR attribute name that can be used as a validation target.
        /// </summary>
        [JsonProperty("fieldName")]
        public Models.ValidatableAttribute FieldName { get; set; }

        /// <summary>
        /// Expected value. For lists, separate values with a comma (e.g. `BRA,PTR`).
        /// </summary>
        [JsonProperty("value")]
        public string MValue { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ValidationRule : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Condition = {this.Condition}");
            toStringOutput.Add($"FieldName = {this.FieldName}");
            toStringOutput.Add($"MValue = {this.MValue ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}