// <copyright file="ValidatableAttribute.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace LogaltyCertificateIssuanceApiCerty.Standard.Models
{
    /// <summary>
    /// ValidatableAttribute.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ValidatableAttribute
    {
        /// <summary>
        /// Type.
        /// </summary>
        [EnumMember(Value = "TYPE")]
        Type,

        /// <summary>
        /// Side.
        /// </summary>
        [EnumMember(Value = "SIDE")]
        Side,

        /// <summary>
        /// Nationality.
        /// </summary>
        [EnumMember(Value = "NATIONALITY")]
        Nationality,

        /// <summary>
        /// Name.
        /// </summary>
        [EnumMember(Value = "NAME")]
        Name,

        /// <summary>
        /// Surname.
        /// </summary>
        [EnumMember(Value = "SURNAME")]
        Surname,

        /// <summary>
        /// IdNumber.
        /// </summary>
        [EnumMember(Value = "ID_NUMBER")]
        IdNumber,

        /// <summary>
        /// DocNumber.
        /// </summary>
        [EnumMember(Value = "DOC_NUMBER")]
        DocNumber,

        /// <summary>
        /// StreetAddress.
        /// </summary>
        [EnumMember(Value = "STREET_ADDRESS")]
        StreetAddress,

        /// <summary>
        /// CityAddress.
        /// </summary>
        [EnumMember(Value = "CITY_ADDRESS")]
        CityAddress,

        /// <summary>
        /// StateAddress.
        /// </summary>
        [EnumMember(Value = "STATE_ADDRESS")]
        StateAddress,

        /// <summary>
        /// Address.
        /// </summary>
        [EnumMember(Value = "ADDRESS")]
        Address,

        /// <summary>
        /// Birthplace.
        /// </summary>
        [EnumMember(Value = "BIRTHPLACE")]
        Birthplace,

        /// <summary>
        /// Parents.
        /// </summary>
        [EnumMember(Value = "PARENTS")]
        Parents,

        /// <summary>
        /// Birthdate.
        /// </summary>
        [EnumMember(Value = "BIRTHDATE")]
        Birthdate,

        /// <summary>
        /// Expiry.
        /// </summary>
        [EnumMember(Value = "EXPIRY")]
        Expiry,

        /// <summary>
        /// Sex.
        /// </summary>
        [EnumMember(Value = "SEX")]
        Sex,

        /// <summary>
        /// Authority.
        /// </summary>
        [EnumMember(Value = "AUTHORITY")]
        Authority,

        /// <summary>
        /// Mrz.
        /// </summary>
        [EnumMember(Value = "MRZ")]
        Mrz,

        /// <summary>
        /// ModelId.
        /// </summary>
        [EnumMember(Value = "MODEL_ID")]
        ModelId,

        /// <summary>
        /// SidesNumber.
        /// </summary>
        [EnumMember(Value = "SIDES_NUMBER")]
        SidesNumber,

        /// <summary>
        /// Surname1.
        /// </summary>
        [EnumMember(Value = "SURNAME1")]
        Surname1,

        /// <summary>
        /// Surname2.
        /// </summary>
        [EnumMember(Value = "SURNAME2")]
        Surname2,

        /// <summary>
        /// Surname1V2.
        /// </summary>
        [EnumMember(Value = "SURNAME1_V2")]
        Surname1V2,

        /// <summary>
        /// Surname2V2.
        /// </summary>
        [EnumMember(Value = "SURNAME2_V2")]
        Surname2V2,

        /// <summary>
        /// DocumentType.
        /// </summary>
        [EnumMember(Value = "DOCUMENT_TYPE")]
        DocumentType
    }
}