// <copyright file="LogaltyCertificateIssuanceApiCertyClient.cs" company="APIMatic">
// LogaltyCertificateIssuanceApiCerty.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Authentication;
using APIMatic.Core.Utilities;
using APIMatic.Core.Utilities.Logger.Configuration;
using LogaltyCertificateIssuanceApiCerty.Standard.Apis;
using LogaltyCertificateIssuanceApiCerty.Standard.Authentication;
using LogaltyCertificateIssuanceApiCerty.Standard.Http.Client;
using LogaltyCertificateIssuanceApiCerty.Standard.Logging;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace LogaltyCertificateIssuanceApiCerty.Standard
{
    /// <summary>
    /// The gateway for the SDK. This class acts as a factory for Api and holds the
    /// configuration of the SDK.
    /// </summary>
    public sealed class LogaltyCertificateIssuanceApiCertyClient : IConfiguration
    {
        // A map of environments and their corresponding servers/baseurls
        private static readonly Dictionary<Environment, Dictionary<Enum, string>> EnvironmentsMap =
            new Dictionary<Environment, Dictionary<Enum, string>>
        {
            {
                Environment.Production, new Dictionary<Enum, string>
                {
                    { Server.Default, "https://{certy_server}" },
                }
            },
            {
                Environment.Environment2, new Dictionary<Enum, string>
                {
                    { Server.Default, "https://{oauth2_server}" },
                }
            },
        };

        private readonly GlobalConfiguration globalConfiguration;
        private SdkLoggingConfiguration sdkLoggingConfiguration;
        private const string userAgent = "DotNet-SDK/0.0.2 (OS: {os-info}, Engine: {engine}/{engine-version})";
        private readonly HttpCallback httpCallback;
        private readonly Lazy<AuthenticationApi> authentication;
        private readonly Lazy<CertificateRequestsApi> certificateRequests;
        private readonly Lazy<EvidenceApi> evidence;
        private readonly Lazy<OperationsApi> operations;

        private LogaltyCertificateIssuanceApiCertyClient(
            Environment environment,
            string certyServer,
            string oauth2Server,
            BearerAuthModel bearerAuthModel,
            BasicAuthModel basicAuthModel,
            HttpCallback httpCallback,
            IHttpClientConfiguration httpClientConfiguration,
            SdkLoggingConfiguration sdkLoggingConfiguration)
        {
            this.Environment = environment;
            this.CertyServer = certyServer;
            this.Oauth2Server = oauth2Server;
            this.httpCallback = httpCallback;
            this.HttpClientConfiguration = httpClientConfiguration;
            this.sdkLoggingConfiguration = sdkLoggingConfiguration;
            BearerAuthModel = bearerAuthModel;
            var bearerAuthManager = new BearerAuthManager(bearerAuthModel);
            BasicAuthModel = basicAuthModel;
            var basicAuthManager = new BasicAuthManager(basicAuthModel);
            globalConfiguration = new GlobalConfiguration.Builder()
                .AuthManagers(new Dictionary<string, AuthManager> {
                    {"bearerAuth", bearerAuthManager},
                    {"basicAuth", basicAuthManager},
                })
                .ApiCallback(httpCallback)
                .HttpConfiguration(httpClientConfiguration)
                .ServerUrls(EnvironmentsMap[environment], Server.Default)
                .LoggingConfig(sdkLoggingConfiguration)
                .Parameters(globalParameter => globalParameter
                    .Template(templateParameter => templateParameter.Setup("certy_server", this.CertyServer))
                    .Template(templateParameter => templateParameter.Setup("oauth2_server", this.Oauth2Server))
                )
                .UserAgent(userAgent)
                .Build();
            BearerAuthCredentials = bearerAuthManager;
            BasicAuthCredentials = basicAuthManager;

            this.authentication = new Lazy<AuthenticationApi>(
                () => new AuthenticationApi(globalConfiguration));
            this.certificateRequests = new Lazy<CertificateRequestsApi>(
                () => new CertificateRequestsApi(globalConfiguration));
            this.evidence = new Lazy<EvidenceApi>(
                () => new EvidenceApi(globalConfiguration));
            this.operations = new Lazy<OperationsApi>(
                () => new OperationsApi(globalConfiguration));
        }

        /// <summary>
        /// Gets AuthenticationApi.
        /// </summary>
        public AuthenticationApi AuthenticationApi => this.authentication.Value;

        /// <summary>
        /// Gets CertificateRequestsApi.
        /// </summary>
        public CertificateRequestsApi CertificateRequestsApi => this.certificateRequests.Value;

        /// <summary>
        /// Gets EvidenceApi.
        /// </summary>
        public EvidenceApi EvidenceApi => this.evidence.Value;

        /// <summary>
        /// Gets OperationsApi.
        /// </summary>
        public OperationsApi OperationsApi => this.operations.Value;

        /// <summary>
        /// Gets the configuration of the Http Client associated with this client.
        /// </summary>
        public IHttpClientConfiguration HttpClientConfiguration { get; }

        /// <summary>
        /// Gets Environment.
        /// Current API environment.
        /// </summary>
        public Environment Environment { get; }

        /// <summary>
        /// Gets CertyServer.
        /// Hostname of the Certy API server.
        /// </summary>
        public string CertyServer { get; }

        /// <summary>
        /// Gets Oauth2Server.
        /// Hostname of the OAuth2 server.
        /// </summary>
        public string Oauth2Server { get; }

        /// <summary>
        /// Gets http callback.
        /// </summary>
        public HttpCallback HttpCallback => this.httpCallback;

        /// <summary>
        /// Gets the credentials to use with BearerAuth.
        /// </summary>
        public IBearerAuthCredentials BearerAuthCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with BearerAuth.
        /// </summary>
        public BearerAuthModel BearerAuthModel { get; private set; }

        /// <summary>
        /// Gets the access token to use with OAuth 2 authentication.
        /// </summary>
        public string AccessToken => this.BearerAuthCredentials.AccessToken;

        /// <summary>
        /// Gets the credentials to use with BasicAuth.
        /// </summary>
        public IBasicAuthCredentials BasicAuthCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with BasicAuth.
        /// </summary>
        public BasicAuthModel BasicAuthModel { get; private set; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends
        /// it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:DEFAULT.</param>
        /// <returns>Returns the baseurl.</returns>
        public string GetBaseUri(Server alias = Server.Default)
        {
            return globalConfiguration.ServerUrl(alias);
        }

        /// <summary>
        /// Creates an object of the LogaltyCertificateIssuanceApiCertyClient using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            Builder builder = new Builder()
                .Environment(this.Environment)
                .CertyServer(this.CertyServer)
                .Oauth2Server(this.Oauth2Server)
                .HttpCallback(httpCallback)
                .LoggingConfig(sdkLoggingConfiguration)
                .HttpClientConfig(config => config.Build());

            if (BearerAuthModel != null)
            {
                builder.BearerAuthCredentials(BearerAuthModel.ToBuilder().Build());
            }

            if (BasicAuthModel != null)
            {
                builder.BasicAuthCredentials(BasicAuthModel.ToBuilder().Build());
            }

            return builder;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return
                $"Environment = {this.Environment}, " +
                $"CertyServer = {this.CertyServer}, " +
                $"Oauth2Server = {this.Oauth2Server}, " +
                $"HttpClientConfiguration = {this.HttpClientConfiguration}, ";
        }

        /// <summary>
        /// Creates the client using builder.
        /// </summary>
        /// <returns> LogaltyCertificateIssuanceApiCertyClient.</returns>
        internal static LogaltyCertificateIssuanceApiCertyClient CreateFromEnvironment()
        {
            var builder = new Builder();

            string environment = System.Environment.GetEnvironmentVariable("LOGALTY_CERTIFICATE_ISSUANCE_API_CERTY_STANDARD_ENVIRONMENT");
            string certyServer = System.Environment.GetEnvironmentVariable("LOGALTY_CERTIFICATE_ISSUANCE_API_CERTY_STANDARD_CERTY_SERVER");
            string oauth2Server = System.Environment.GetEnvironmentVariable("LOGALTY_CERTIFICATE_ISSUANCE_API_CERTY_STANDARD_OAUTH_2_SERVER");
            string accessToken = System.Environment.GetEnvironmentVariable("LOGALTY_CERTIFICATE_ISSUANCE_API_CERTY_STANDARD_ACCESS_TOKEN");
            string username = System.Environment.GetEnvironmentVariable("LOGALTY_CERTIFICATE_ISSUANCE_API_CERTY_STANDARD_USERNAME");
            string password = System.Environment.GetEnvironmentVariable("LOGALTY_CERTIFICATE_ISSUANCE_API_CERTY_STANDARD_PASSWORD");

            if (environment != null)
            {
                builder.Environment(CoreHelper.JsonDeserialize<Environment>($"\"{environment}\""));
            }

            if (certyServer != null)
            {
                builder.CertyServer(certyServer);
            }

            if (oauth2Server != null)
            {
                builder.Oauth2Server(oauth2Server);
            }

            if (accessToken != null)
            {
                builder.BearerAuthCredentials(new BearerAuthModel
                .Builder(accessToken)
                .Build());
            }

            if (username != null && password != null)
            {
                builder.BasicAuthCredentials(new BasicAuthModel
                .Builder(username, password)
                .Build());
            }

            return builder.Build();
        }

        /// <summary>
        /// Creates the client from configuration.
        /// </summary>
        /// <returns> LogaltyCertificateIssuanceApiCertyClient.</returns>
        public static LogaltyCertificateIssuanceApiCertyClient FromConfiguration(IConfigurationSection configuration) =>
            Builder.FromConfiguration(configuration).Build();

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private Environment _environment = LogaltyCertificateIssuanceApiCerty.Standard.Environment.Production;
            private string _certyServer = "certy_server";
            private string _oauth2Server = "oauth2_server";
            private BearerAuthModel _bearerAuthModel = new BearerAuthModel();
            private BasicAuthModel _basicAuthModel = new BasicAuthModel();
            private HttpClientConfiguration.Builder _httpClientConfig = new HttpClientConfiguration.Builder();
            private HttpCallback _httpCallback;
            private SdkLoggingConfiguration _sdkLoggingConfiguration;

            /// <summary>
            /// Sets credentials for BearerAuth.
            /// </summary>
            /// <param name="bearerAuthModel">BearerAuthModel.</param>
            /// <returns>Builder.</returns>
            public Builder BearerAuthCredentials(BearerAuthModel bearerAuthModel)
            {
                _bearerAuthModel = bearerAuthModel ??
                    throw new ArgumentNullException(nameof(bearerAuthModel));
                return this;
            }

            /// <summary>
            /// Sets credentials for BasicAuth.
            /// </summary>
            /// <param name="basicAuthModel">BasicAuthModel.</param>
            /// <returns>Builder.</returns>
            public Builder BasicAuthCredentials(BasicAuthModel basicAuthModel)
            {
                _basicAuthModel = basicAuthModel ??
                    throw new ArgumentNullException(nameof(basicAuthModel));
                return this;
            }

            /// <summary>
            /// Sets Environment.
            /// </summary>
            /// <param name="environment"> Environment. </param>
            /// <returns> Builder. </returns>
            public Builder Environment(Environment environment)
            {
                _environment = environment;
                return this;
            }

            /// <summary>
            /// Sets CertyServer.
            /// </summary>
            /// <param name="certyServer"> CertyServer. </param>
            /// <returns> Builder. </returns>
            public Builder CertyServer(string certyServer)
            {
                _certyServer = certyServer ?? throw new ArgumentNullException(nameof(certyServer));
                return this;
            }

            /// <summary>
            /// Sets Oauth2Server.
            /// </summary>
            /// <param name="oauth2Server"> Oauth2Server. </param>
            /// <returns> Builder. </returns>
            public Builder Oauth2Server(string oauth2Server)
            {
                _oauth2Server = oauth2Server ?? throw new ArgumentNullException(nameof(oauth2Server));
                return this;
            }

            /// <summary>
            /// Sets HttpClientConfig.
            /// </summary>
            /// <param name="action"> Action. </param>
            /// <returns>Builder.</returns>
            public Builder HttpClientConfig(Action<HttpClientConfiguration.Builder> action)
            {
                if (action is null)
                {
                    throw new ArgumentNullException(nameof(action));
                }

                action(_httpClientConfig);
                return this;
            }

            private Builder HttpClientConfig(HttpClientConfiguration.Builder httpClientConfigurationBuilder)
            {
                if (httpClientConfigurationBuilder != null)
                {
                    _httpClientConfig = httpClientConfigurationBuilder;
                }

                return this;
            }

            /// <summary>
            /// Sets the default logging configuration, using the Console logger.
            /// </summary>
            /// <returns>Builder.</returns>
            public Builder LoggingConfig()
            {
                _sdkLoggingConfiguration = SdkLoggingConfiguration.Console();
                return this;
            }

            /// <summary>
            /// Sets the logging configuration using the provided <paramref name="action"/>.
            /// </summary>
            /// <param name="action">The action to perform on the logging configuration builder.</param>
            /// <returns>Builder.</returns>
            /// <exception cref="ArgumentNullException">Thrown when <paramref name="action"/> is null.</exception>
            public Builder LoggingConfig(Action<LogBuilder> action)
            {
                if (action is null) throw new ArgumentNullException(nameof(action));
                var logBuilder =
                    LogBuilder.CreateFromConfig(_sdkLoggingConfiguration ?? SdkLoggingConfiguration.Console());
                action(logBuilder);
                _sdkLoggingConfiguration = logBuilder.Build();
                return this;
            }

            internal Builder LoggingConfig(SdkLoggingConfiguration configuration)
            {
                _sdkLoggingConfiguration = configuration;
                return this;
            }

            /// <summary>
            /// Sets the HttpCallback for the Builder.
            /// </summary>
            /// <param name="httpCallback"> http callback. </param>
            /// <returns>Builder.</returns>
            public Builder HttpCallback(HttpCallback httpCallback)
            {
                _httpCallback = httpCallback;
                return this;
            }

            /// <summary>
            /// Creates an object of the LogaltyCertificateIssuanceApiCertyClient using the values provided for the builder.
            /// </summary>
            /// <returns>LogaltyCertificateIssuanceApiCertyClient.</returns>
            public LogaltyCertificateIssuanceApiCertyClient Build()
            {
                if (_bearerAuthModel.AccessToken == null)
                {
                    _bearerAuthModel = null;
                }
                if (_basicAuthModel.Username == null || _basicAuthModel.Password == null)
                {
                    _basicAuthModel = null;
                }
                return new LogaltyCertificateIssuanceApiCertyClient(
                    _environment,
                    _certyServer,
                    _oauth2Server,
                    _bearerAuthModel,
                    _basicAuthModel,
                    _httpCallback,
                    _httpClientConfig.Build(),
                    _sdkLoggingConfiguration);
            }

            /// <summary>
            /// Creates the client builder from configuration.
            /// </summary>
            /// <returns> Builder.</returns>
            public static Builder FromConfiguration(IConfigurationSection config)
            {
                var builder = new Builder();
                var options = config.Get<LogaltyCertificateIssuanceApiCertyClientOptions>();
                if (options == null) return builder;
                if (options.Environment != null)
                    builder.Environment(options.Environment.Value);
                if (options.CertyServer != null)
                    builder.CertyServer(options.CertyServer);
                if (options.Oauth2Server != null)
                    builder.Oauth2Server(options.Oauth2Server);
                if (options.BearerAuthCredentials != null)
                    builder.BearerAuthCredentials(BearerAuthModel.FromOptions(options.BearerAuthCredentials));
                if (options.BasicAuthCredentials != null)
                    builder.BasicAuthCredentials(BasicAuthModel.FromOptions(options.BasicAuthCredentials));
                if (options.HttpClientConfig != null)
                    builder.HttpClientConfig(Http.Client.HttpClientConfiguration.FromOptions(options.HttpClientConfig));
                if (options.LoggingConfig != null)
                    builder.LoggingConfig(LogBuilder.FromOptions(options.LoggingConfig));
                return builder;
            }
        }

        public class LogaltyCertificateIssuanceApiCertyClientOptions
        {
            public Environment? Environment { get; set; }
            public string CertyServer { get; set; }
            public string Oauth2Server { get; set; }
            public BearerAuthModelOptions BearerAuthCredentials { get; set; }
            public BasicAuthModelOptions BasicAuthCredentials { get; set; }
            public HttpClientConfigurationOptions HttpClientConfig { get; set; }
            public LoggingConfigOptions LoggingConfig { get; set; }
        }
    }
}
